#!/usr/bin/env python3
"""Run every case in the registry with `trace.py` standing in for the ccusage fixture, and
write what each one asked the fixture for.

Output is `traces.json`: `{case name: [{mode, argv}, ...]}` in registry order, plus the
deduplicated key set the artifact generator needs.

This reuses `capture.py`'s environment construction on purpose. The environment a child sees
is the thing that decides what it prints, and building a second version of it here is exactly
how the recorded trace would stop describing the run the goldens came from. The INDEPENDENT
half of this system is the verifier, which shares nothing — see verify.py.

Run: python3 tests/oracle/record.py [--out tests/oracle/traces.json]
"""
import json
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
TESTS = os.path.dirname(HERE)
REPO = os.path.dirname(TESTS)
sys.path.insert(0, os.path.join(TESTS, "golden"))
sys.path.insert(0, os.path.join(TESTS, "harness"))

import capture  # noqa: E402  (path set above)
import fixtures  # noqa: E402

TRACE = os.path.join(HERE, "trace.py")
INVENTORY = os.path.join(HERE, "inventory.json")
DEFAULT_OUT = os.path.join(HERE, "traces.json")

with open(INVENTORY) as _fh:
    _INV = json.load(_fh)
DEFAULT_ANCHOR = _INV["defaultAnchor"]


def anchor_for(case):
    """The wall clock to run a case at.

    Stored-golden cases carry their own `captureAnchor` and MUST use it: their child argv is
    what produced the committed golden, and recording them at a different date would build an
    artifact set that cannot serve the very replay it exists for.

    The other 73 cases have no anchor because tests-ts/parity.mjs runs them live. A live anchor
    is unusable here — see inventory.json's $anchorComment — so they get the declared fixed one.
    """
    return case.get("captureAnchor") or DEFAULT_ANCHOR


def record_case(case, codex_home, fixture_home, trace_out):
    """One case, through the same wrapper capture.py uses, with the recorder in place."""
    open(trace_out, "w").close()

    extra = {
        "CCUSAGE_CMD": f"{sys.executable} {TRACE}",
        "FAKE_MODE": case["mode"],
        "USAGE_CONFIG": capture.FIXTURE_CONFIG,
        "SPENDBAR_TRACE_OUT": trace_out,
    }
    if case["codexFixture"]:
        extra["CODEX_HOME"] = codex_home
    # extraEnv LAST, matching capture.py — err_missing_binary's deliberately broken
    # CCUSAGE_CMD must still win here, or the case that proves the missing-binary path would
    # quietly start succeeding against the recorder.
    extra.update(case["extraEnv"])

    anchor = anchor_for(case)
    argv = [sys.executable, capture.WRAPPER, "--anchor", anchor, "--", *case["argv"]]
    proc = subprocess.run(
        argv, capture_output=True, text=True,
        env=capture.child_env(fixture_home, extra))

    calls = []
    with open(trace_out) as fh:
        for line in fh:
            line = line.strip()
            if line:
                calls.append(json.loads(line))
    return calls, proc.returncode


def main():
    out_path = DEFAULT_OUT
    if "--out" in sys.argv:
        out_path = sys.argv[sys.argv.index("--out") + 1]

    fixture_home = fixtures.build_fixture_home()
    codex_home, outside = fixtures.build_codex_home(fixture_home)

    traces = {}
    exits = {}
    anchors = {}
    try:
        with tempfile.TemporaryDirectory(prefix="spendbar-trace-") as tmp:
            trace_out = os.path.join(tmp, "trace.jsonl")
            for case in capture.REGISTRY["cases"]:
                calls, code = record_case(case, codex_home, fixture_home, trace_out)
                traces[case["name"]] = calls
                exits[case["name"]] = code
                anchors[case["name"]] = anchor_for(case)
    finally:
        import shutil
        for d in (fixture_home, codex_home, outside):
            shutil.rmtree(d, ignore_errors=True)

    # The deduplicated (mode, argv) set is what the artifact generator has to cover. Sorted so
    # the file is stable across runs; a diff here should mean the oracle's call pattern moved,
    # never that a dict iterated differently.
    keys = sorted(
        {(c["mode"], tuple(c["argv"])) for calls in traces.values() for c in calls})
    payload = {
        "$comment": (
            "GENERATED by tests/oracle/record.py — do not hand-edit. Observed child calls per "
            "case. This is evidence, not authority: inventory.json declares what should "
            "happen, and build.py --check compares the two."),
        "cases": traces,
        "exitCodes": exits,
        # Recorded because --since/--until are resolved against it: the same case at a different
        # anchor produces different child argv, so a trace without its anchor cannot be checked.
        "anchors": anchors,
        "keys": [{"mode": m, "argv": list(a)} for m, a in keys],
    }
    with open(out_path, "w") as fh:
        json.dump(payload, fh, indent=1, sort_keys=True)
        fh.write("\n")

    called = sum(1 for v in traces.values() if v)
    print(f"recorded {len(traces)} cases; {called} made child calls; "
          f"{len(keys)} distinct (mode, argv) keys -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
